#include "clang-nichecker/Passes/SourceEmissionPass.h"
#include "clang-nichecker/Support/SourceUtils.h"
#include "llvm/Support/FormatVariadic.h"

using namespace llvm;

namespace clang::nichecker {

static std::string buildCompatibilityPrelude(llvm::StringRef OriginalSource,
                                             llvm::StringRef CurrentSource,
                                             bool NeedsPthreadWrapper) {
  std::string Prelude;
  raw_string_ostream OS(Prelude);
  bool AddedAnything = false;

  if (CurrentSource.contains("assert(") &&
      !hasHeaderInclude(CurrentSource, "assert.h")) {
    OS << "#include <assert.h>\n";
    AddedAnything = true;
  }

  if (CurrentSource.contains("NULL") &&
      !hasHeaderInclude(CurrentSource, "stddef.h")) {
    OS << "#include <stddef.h>\n";
    AddedAnything = true;
  }

  if (NeedsPthreadWrapper && !hasHeaderInclude(OriginalSource, "pthread.h") &&
      !hasPthreadTypedefLike(OriginalSource)) {
    OS << "typedef int pthread_t;\n";
    AddedAnything = true;
  }

  if (AddedAnything)
    OS << "\n";
  return OS.str();
}

static std::string buildGeneratedHeader(const PipelineOptions &Options,
                                        const TransformResult &Result) {
  return formatv(
             "/*\n"
             " * generated by clang-nichecker\n"
             " * input: {0}\n"
             " * detected-kind: {1}\n"
             " * thread-entry-functions: {2}\n"
             " * interrupt-functions: {3}\n"
             " * notes: {4}\n"
             " */\n\n",
             Options.InputPath, toString(Result.Summary.Kind),
             joinList(Result.Summary.ThreadEntryFunctions),
             joinList(Result.Summary.InterruptFunctions),
             joinNotes(Result.Notes))
      .str();
}

llvm::StringRef SourceEmissionPass::name() const { return "source-emission"; }

llvm::Error SourceEmissionPass::run(const PipelineContext &Context,
                                    TransformResult &Result) const {
  Result.Source = Context.OriginalSource.str();
  applyReplacements(Result.Source, Result.PendingReplacements);

  bool NeedsPthreadWrapper = Result.Summary.Kind == ProgramKind::InterruptDriven;
  std::string Header = buildGeneratedHeader(Context.Options, Result);
  std::string Prelude =
      buildCompatibilityPrelude(Context.OriginalSource, Result.Source,
                                NeedsPthreadWrapper);
  Result.Source = Header + Prelude + Result.Source;
  return Error::success();
}

} // namespace clang::nichecker
